#### 数据清洗

- 处理缺失值

In [1]:
import pandas as pd
import numpy as np

string_data = pd.Series(['adea', np.nan, 'bob', 'asddad'])

In [3]:
string_data

0      adea
1       NaN
2       bob
3    asddad
dtype: str

In [4]:
string_data.isnull()

0    False
1     True
2    False
3    False
dtype: bool

In [6]:
string_data[0] = None

In [7]:
string_data.isnull()

0     True
1     True
2    False
3    False
dtype: bool

- 滤除缺失数据

In [10]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])

data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notnull()] # 同上

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
df = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

In [15]:
df

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
df.dropna() # just one column's all rows aren't NA

     0    1    2
0  1.0  6.5  3.0

In [20]:
df.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df[4] = NA
print(df)
df.dropna(axis=1, how='all') # 丢弃列，只需传入axis = 1

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [24]:
df1 = pd.DataFrame(np.random.randn(7, 3))
df1.iloc[:4, 1] = NA
df1.iloc[:2, 2] = NA

df1

          0         1         2
0 -0.814689       NaN       NaN
1 -1.215060       NaN       NaN
2  0.181172       NaN  0.623230
3 -0.899735       NaN -0.861927
4 -1.678795 -0.432911 -0.130703
5  0.317591 -0.093650  0.620645
6 -0.982384 -1.690891  0.063446

In [27]:
df1.dropna()

          0         1         2
4 -1.678795 -0.432911 -0.130703
5  0.317591 -0.093650  0.620645
6 -0.982384 -1.690891  0.063446

In [31]:
df1.dropna(thresh=2)

          0         1         2
2  0.181172       NaN  0.623230
3 -0.899735       NaN -0.861927
4 -1.678795 -0.432911 -0.130703
5  0.317591 -0.093650  0.620645
6 -0.982384 -1.690891  0.063446

- 填充缺失数据

In [32]:
df1.fillna(0)

          0         1         2
0 -0.814689  0.000000  0.000000
1 -1.215060  0.000000  0.000000
2  0.181172  0.000000  0.623230
3 -0.899735  0.000000 -0.861927
4 -1.678795 -0.432911 -0.130703
5  0.317591 -0.093650  0.620645
6 -0.982384 -1.690891  0.063446

In [34]:
df1.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.814689  0.500000  0.000000
1 -1.215060  0.500000  0.000000
2  0.181172  0.500000  0.623230
3 -0.899735  0.500000 -0.861927
4 -1.678795 -0.432911 -0.130703
5  0.317591 -0.093650  0.620645
6 -0.982384 -1.690891  0.063446

In [35]:
_ = df1.fillna(0, inplace=True)

In [36]:
df1

          0         1         2
0 -0.814689  0.000000  0.000000
1 -1.215060  0.000000  0.000000
2  0.181172  0.000000  0.623230
3 -0.899735  0.000000 -0.861927
4 -1.678795 -0.432911 -0.130703
5  0.317591 -0.093650  0.620645
6 -0.982384 -1.690891  0.063446

In [44]:
data = pd.Series([1., NA, 3.5, NA, 7])

data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

### 数据转换

- #### 移除重复数据

In [48]:
data1 = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})

data1

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [51]:
data1.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [52]:
data1.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

- #### 利用函数或映射进行数据转换

In [53]:
data_map = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'Bacon'], 'ounces': [4, 3, 12, 6, 7.5, 8, 9]})

data_map

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6        Bacon     9.0

In [59]:
meat_to_animal = {'bacon': 'pig', 'pulled pork': 'pig', 'pastrami': 'cow', 'corned beef': 'cow', 'honey ham': 'pig', 'nova lox': 'salmon'}

In [56]:
lowercased = data_map['food'].str.lower()

lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6          bacon
Name: food, dtype: str

In [61]:
data_map['animal'] = lowercased.map(meat_to_animal)

data_map

          food  ounces animal
0        bacon     4.0    pig
1  pulled pork     3.0    pig
2        bacon    12.0    pig
3     Pastrami     6.0    cow
4  corned beef     7.5    cow
5        Bacon     8.0    pig
6        Bacon     9.0    pig

- #### 替换值

In [62]:
data_replace = pd.Series([1., -999., 2., -999., -1000., 3.])

data_replace

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [63]:
data_replace.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64