### pandas的数据结构介绍

#### Series

In [3]:
import pandas as pd
obj = pd.Series([1, 2, 3, 4, 5])
obj
obj.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
obj.values

obj.index #like range(5)

RangeIndex(start=0, stop=5, step=1)

In [5]:
obj2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
obj2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
obj2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [7]:
print(obj2['b'])
obj2['b'] = 7
obj2

2

a    1
b    7
c    3
d    4
e    5
dtype: int64

In [8]:
obj2[obj2 > 5]

b    7
dtype: int64

In [9]:
obj2[['a', 'c', 'd']]

a    1
c    3
d    4
dtype: int64

In [10]:
'g' in obj2

False

In [11]:
'a' in obj2

True

可以直接通过字典来创建Series

In [12]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [13]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

obj4 =pd.Series(sdata, index=states)

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [14]:
obj4['California'] = 45000

In [15]:
obj4

California    45000.0
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

### DataFrame

In [18]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
        }

frame = pd.DataFrame(data) # 等长列表或NumPy数组组成的字典

In [19]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [20]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [22]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])

In [24]:
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [26]:
frame2['state']  # 通过列名获取列

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: str

In [28]:
frame2.year # 通过列名获取列

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [31]:
frame2.loc['three'] # 用loc属性获取行

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [37]:
del frame2['debt']

KeyError: 'debt'

In [36]:
frame2.columns

Index(['year', 'state', 'pop'], dtype='str')

In [40]:
pop = {'Nevada':{2001: 2.4, 2002: 2.9},
       'Ohio':{2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [41]:
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [45]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [48]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [49]:
pd.DataFrame(pdata)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [53]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [54]:
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [55]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

### 索引对象

In [56]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

index = obj.index

In [57]:
index

Index(['a', 'b', 'c'], dtype='str')

In [58]:
index[1:]

Index(['b', 'c'], dtype='str')

In [59]:
obj

a    0
b    1
c    2
dtype: int64

In [61]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [62]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [64]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

obj3

0      blue
2    purple
4    yellow
dtype: str

In [66]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [67]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: str

In [70]:
import numpy as np
frame4 = pd.DataFrame(np.arange(9).reshape(3, 3), index=['a', 'b', 'c'], columns=['Ohio', 'Texas', 'California'])

frame4

   Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [72]:
frame5 = frame4.reindex(['a', 'b', 'c', 'd'])
frame5

   Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [77]:
new_obj3 = obj3.drop(0)
new_obj3

2    purple
4    yellow
dtype: str

In [78]:
data1 = pd.DataFrame(np.arange(16).reshape(4, 4), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

data1

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
data1.drop(['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [81]:
data1.drop('two', axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### 索引、选取和过滤

In [85]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [83]:
obj['b'] # 通过索引获取值

np.float64(1.0)

In [89]:
obj.iloc[1]# 通过位置索引

np.float64(1.0)

In [90]:
obj.iloc[2:4] # 不包含尾端

c    2.0
d    3.0
dtype: float64

In [92]:
obj[['b', 'd', 'a']]

b    1.0
d    3.0
a    0.0
dtype: float64

In [95]:
obj['a':'c'] # 包含尾端

a    0.0
b    1.0
c    2.0
dtype: float64

### 用loc和iloc进行选取

In [96]:
data1.loc['Colorado',['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [98]:
data1.iloc[2, [3, 0, 1]] # 第三行，第4、1、2列

four    11
one      8
two      9
Name: Utah, dtype: int64

In [99]:
data1.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

### 算术运算和数据对齐

In [102]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
print(s1,s2)
s1 + s2

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64 a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [106]:
# dataframe
df1 = pd.DataFrame(np.arange(9.).reshape(3, 3), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Colorado'])
print(df1)
print(df2)
df1+df2

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
            b     d     e
Utah      0.0   1.0   2.0
Ohio      3.0   4.0   5.0
Texas     6.0   7.0   8.0
Colorado  9.0  10.0  11.0

             b   c     d   e
Colorado  15.0 NaN  18.0 NaN
Ohio       3.0 NaN   6.0 NaN
Texas      9.0 NaN  12.0 NaN
Utah       NaN NaN   NaN NaN

### 在算术方法中填充值

In [107]:
df3 = pd.DataFrame(np.arange(12.).reshape(3, 4), columns=list('abcd'))
df4 = pd.DataFrame(np.arange(20.).reshape(4, 5), columns=list('abcde'))

df4.loc[1, 'b'] = np.nan

print(df3)
print(df4)

df3 + df4

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [109]:
df3.add(df4, fill_value = 0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0